# Generated by Django 4.2.2 on 2023-06-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('member_count', models.PositiveSmallIntegerField(default=1)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='coordinator.coordinator')),
            ],
        ),
    ]
